### ISSUE TITLE
Enhancement request - Don't make me push the button!

### ISSUE THREAD

**Issue by grahamduthie** [lpgm/ft-extension#1]
It would be nice for the extension to run automatically whenever I browse to a new page on the ft.com domain.

**Comment by grahamduthie** [comment]
This might help...

https://stackoverflow.com/questions/9899125/chrome-extension-autorun

**Comment by lpgm** [comment]
Your wish is my command! The cookie box should disappear automatically now. And if it doesn't, click the FT extension icon and then it should.
